
#docker-compose -f environment.yml up -d mq_main
version: '2.1'
services:
  mq_main:
    image: mysql:latest
    ports:
    - "3316:3306"
    command: --init-file /data/application/init.sql
    volumes:
    - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mq_main
      MYSQL_USER: developer

